 #cloud-config                                                                                            ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true
packages:
  - nginx
runcmd:
  - [ systemctl, nginx-reload ]
  - [ systemctl, enable, nginx.service ]
  - [ systemctl, start, --no-block, nginx.service ]
  - [ sh, -c, "echo $(hostname | cut -d '.' -f 1 ) > /var/www/html/index.html" ]
  - [ sh, -c, "echo $(ip add ) >> /var/www/html/index.html" ]

users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4A9l1KcVuOxeprkVOEj98IkcfuPA79BLWsdtbIhJoUHd3VlM/fU1ok9Y0$

      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4A9l1KcVuOxeprkVOEj98IkcfuPA79BLWsdtbIhJoUHd3VlM/fU1ok9Y0$